### PR TITLE
add in support for udt

### PR DESCRIPTION
**Pull request by whyrusleeping**

### CODE REVIEW

**Comment by whyrusleeping** [comment]
after looking through the test failures, i realize we have different ideas of how a udt multiaddr should be represented. thoughts?

**Comment by whyrusleeping** [comment]
my thought was that udt addresses would look like: `/ip4/4.5.6.7/udt/2222`, but i think that you were expecting `/ip4/4.5.6.7/udp/2222/udt` which makes sense too.

**Comment by jbenet** [comment]
```
/ip4/4.5.6.7/udp/2222/udt
```
o/ that one

**Comment by jbenet** [comment]
i had support for UTP already, i think so it shouldn't be too difficult to replicate all the utp parts and s/utp/udt

**Comment by whyrusleeping** [comment]
yeah... i ended up clobbering some things to make it work 'my way'. whoops.

**Comment by whyrusleeping** [comment]
nvm. didnt need to change anything apparently.

**Comment by jbenet** [comment]
yeah i thought i had it there already

**Pull request closed without merging**
